### ISSUE TITLE
Harvard-Oxford cortical + thoughts

### ISSUE THREAD

**Issue by richardbeare** [LCBC-UiO/ggseg#10]
Hi,
I've been working on a ggseg version of the Harvard Oxford atlas, cortical only at the moment. Hopefully it hasn't already appeared somewhere. I am wondering what the preferred approach to providing my data/methods is - PR to ggsegExtra?

I've developed some procedures that don't rely on commercial tools for the conversion process. My approach, outlined below, uses freesurfer + imagemagick + R geospatial tools.

I am hoping these will be useful too. Please let me know if there's a sensible place to add them in the ggseg repos.

Finally, the simple features geom (`geom_sf`), is now part of ggplot2. It may simplify your package a lot if you use it rather than `geom_polygon`. It will certainly make the atlas data frame look smaller, because the polygons are captured in a special geometry column, thus the atlas only needs a row per region per view, rather than one per boundary point. It also naturally handles broken regions.

My procedure for HO atlas:
1. Create a freesurfer ctab file to match the HO cortical atlas.
1. Import the 25% 1mm atlas into fsaverage space via freesurfer commands - ends up with an annotation file, with many gaps due to imperfections in the alignment.
1. Fill the gaps and smooth the boundaries via surface morphology in connectome workbench
1. Use tksurfer visualization tool + bash + tcl to auto capture a series of lateral and medial pictures with one region in each. Make the region red.
1. imagemagick to transform colourspace for simple segmentation and throw away isolated pixels that survive thresholding.
1. Suck into R via the raster package and convert to polygons using simple features framework.

Default plot of the sf version as well as the ggseg version derived from the sf version:
![ho sf](https://user-images.githubusercontent.com/780449/55443863-01b2e200-5600-11e9-9d9e-b907ec3a23df.jpg)
![ho gg](https://user-images.githubusercontent.com/780449/55443867-07a8c300-5600-11e9-822f-0a6229fea29a.jpg)

**Comment by Athanasiamo** [comment]
This is great work! Thank you for figuring out another pipeline to get the atlas data into shape! We will definitely be trying it out! You are also very welcome to PR your above description to the wiki as another way of creating atlases.

A PR to ggsegExtra would be great, then I can run some checks and release it during this week likely.

Thanks for the tip about geom_sf. I went away from that as I experienced the polygons to be a little quicker. But I have been playing with altering the ggseg_atlas class into a nested-type data.frame that would be easier and more familiar for people in general to work with, hiding away certain data into the nested structure that users in general not need to worry about.

**Comment by Athanasiamo** [comment]
oh, and one thing! Could you please also add the medial wall into the atlas? We found it is more familiar and easier to view when the medial wall is included in the plots, but with <NA> as labels/area specifications.

**Comment by richardbeare** [comment]
Do you have a preference as to where in the ggsegExtra source tree I should put non R scripts?

**Comment by Athanasiamo** [comment]
hm, I think perhaps if you make a sub-folder in the data-raw folder for now, and i'll have a real think about how I want to organise this once I see the scripts etc. Sound good?

**Comment by richardbeare** [comment]
OK, will do.
