### ISSUE TITLE
symmetrical subcortical structures?

### ISSUE THREAD

**Issue by RMBrouwer** [LCBC-UiO/ggseg#12]
Thanks so much for this wonderful package! 

I have been struggling though, to get subcortical plots: a standard call to the aseg atlas provided me with symmetrical images. When looking into the atlas, I noticed that something odd seems to happen (at least to me) with the labeling: There are right-hemisphere area's with a "Left-..." label (see an example below) and these are plotted onto the brain instead of the right hemisphere areas with a "Right-..." label. I changed these labels on my data to plot and then all worked perfectly. Maybe there is some rationale for this, but it could be good to make this explicit for the users? 

Best wishes, and thanks, 
Rachel 
[I am using ggseg 1.5.1]

 > aseg
# A tibble: 34 x 6
   atlas area              hemi  side  label                   ggseg               
   <chr> <chr>             <chr> <chr> <fct>                   <list>              
 1 aseg  <NA>              right axial <NA>                    <tibble [808 × 5]>  
 2 aseg  <NA>              left  axial <NA>                    <tibble [1,014 × 5]>
 3 aseg  thalamus proper   left  axial Left-Thalamus-Proper    <tibble [56 × 5]>   
 4 aseg  thalamus proper   left  axial Right-Thalamus-Proper   <tibble [56 × 5]>   
 5 aseg  thalamus proper   right axial Left-Thalamus-Proper    <tibble [61 × 5]>   
 6 aseg  thalamus proper   right axial Right-Thalamus-Proper   <tibble [61 × 5]>   
...

**Comment by RMBrouwer** [comment]
Perfect, thank you!

**Comment by Athanasiamo** [comment]
Thanks again for seeing and reporting this. It has now been fixed in commit [3211ecec](https://github.com/LCBC-UiO/ggseg/commit/3211ecec7b345de6beb898a201142f4725bee287)
