### ISSUE TITLE
Error using 3.6.0

### ISSUE THREAD

**Issue by wrenwood** [LCBC-UiO/ggseg#15]
I've had no issues with ggseg in the past. I recently updated to R 3.6.0. Now when I run my code I get an error that says "Error in FUN(X[[i]], ...) : object '.id' not found"

**Comment by Athanasiamo** [comment]
hi. please give it another go now after updating a change in a dependence broke bits of the code, but that should be fixed now.

**Comment by rowenachz** [comment]
Hi, I have a similar issue where I tried downloading ggsegExtra on 3.6.0 with the suggested command - ggseg::install_atlases() but was thrown the error Error: 'install_atlases' is not an exported object from 'namespace:ggseg'.

**Comment by Athanasiamo** [comment]
Hi! Thanks for letting us know. We forgot to tag that function to be visible to the user (it was working fine in dev-mode), which is why it did not work for you. That is not amended, and should be working.

**Comment by gsborgeest** [comment]
Hi, this issue has just come up here, too. I'm getting this error on code that used to run just fine. 

Error in FUN(X[[i]], ...) : object '.id' not found 

Running R version 3.6.3 (2020-02-29), and just re-installed ggseg, too.

**Comment by Athanasiamo** [comment]
What commands are you using that create this problem? Everything seems to be working on my end, so I'll need more information to help you figure it out.

**Comment by gsborgeest** [comment]
This one for example. As I said, it worked fine from my lab computer but doesn't at home, not sure if pc vs. mac could make a difference? Thank you!

ggseg(data=sig, mapping=aes(fill=age_estimate), colour='black', hemisphere='right', position='stacked') + theme_void() + scale_fill_viridis(limits = range(-0.8, 0.8)) + 
  labs(title="Total Grey Matter - Age", subtitle = "p < 0.05, FDR corrected") +
  theme(legend.position = "none", plot.title = element_text(size = 15), plot.subtitle = element_text(size = 13))

**Comment by Athanasiamo** [comment]
can you please tell me the output of

```
packageVersion("ggseg")
```

Thanks!

**Comment by gsborgeest** [comment]
‘1.5.3’

**Comment by Athanasiamo** [comment]
you are still on an older version of ggseg, so this seems like an incompatibility issue. The newest version is 1.5.5. 

Please try reinstalling

```r
remotes::install_github("LCBC-UiO/ggseg", build_vignetttes = FALSE)
```

**Comment by gsborgeest** [comment]
Thanks for your help! I just did, and then restarted R, but am still getting the same error message...

**Comment by Athanasiamo** [comment]
hm ok. 

what happens if you only run `ggseg()` no extra commands?

**Comment by gsborgeest** [comment]
that works just fine

**Comment by Athanasiamo** [comment]
then there is something in the data you are using that is messing things up somehow. 
Since I dont know how your data looks like, its hard to know what.

``` r
library(ggseg)
#> Loading required package: ggplot2

ggseg()
```

![](https://i.imgur.com/2wXZRYF.png)

``` r

someData <- data.frame(
  region = c("transverse temporal", "insula",
             "precentral","superior parietal"),
  p = sample(seq(0,.5,.001), 4),
  stringsAsFactors = FALSE
  )

ggseg(someData, atlas = dk, mapping = aes(fill = p))
```

![](https://i.imgur.com/JxKxNlg.png)

<sup>Created on 2020-09-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by gsborgeest** [comment]
Very strange, yours works fine. 

I've tried various other datasets, all of which used to work fine on the other machine, kept getting the same error (even when using the same column names as yours). 

I then re-installed the brainGraph package because I realised that `data("dkt") ` did not run. Now I am getting a different error message:

`ggseg(data=sig, atlas=dk, mapping=aes(fill=fldin_estimate))`

```
> ggseg(data=sig, atlas=dk, mapping=aes(fill=fldin_estimate))
Error in as_ggseg_atlas(geobrain) : 
  There are missing necessary columns in the data.frame for it to be a ggseg_atlas: '.long' '.lat' '.id' '.subid' 'atlas' 'region' 'side'
In addition: Warning message:
In ggseg(data = sig, atlas = dk, mapping = aes(fill = fldin_estimate)) :
  This is not a ggseg_atlas-class. Attempting to convert with `as_ggseg_atlas()`

```
I checked the spelling of my `sig$region` column, and it seems to be correct. Could you remind me how to extract the ggseg atlas spelling again, just so I can be sure? Is there anything else you can think of that I should do?


Sorry to bother you with this, A! Thanks.

**Comment by Athanasiamo** [comment]
the atlases are data, so you can inspect them as such:

``` r
library(ggseg)
#> Loading required package: ggplot2

dk
#> # A tibble: 90 x 6
#>    atlas hemi  region              side    label                ggseg           
#>    <chr> <chr> <chr>               <chr>   <chr>                <list>          
#>  1 dk    left  <NA>                lateral <NA>                 <tibble [24 × 7…
#>  2 dk    left  bankssts            lateral lh_bankssts          <tibble [79 × 7…
#>  3 dk    left  caudal middle fron… lateral lh_caudalmiddlefron… <tibble [102 × …
#>  4 dk    left  fusiform            lateral lh_fusiform          <tibble [60 × 7…
#>  5 dk    left  inferior parietal   lateral lh_inferiorparietal  <tibble [116 × …
#>  6 dk    left  inferior temporal   lateral lh_inferiortemporal  <tibble [182 × …
#>  7 dk    left  lateral occipital   lateral lh_lateraloccipital  <tibble [85 × 7…
#>  8 dk    left  lateral orbitofron… lateral lh_lateralorbitofro… <tibble [70 × 7…
#>  9 dk    left  middle temporal     lateral lh_middletemporal    <tibble [188 × …
#> 10 dk    left  pars opercularis    lateral lh_parsopercularis   <tibble [82 × 7…
#> # … with 80 more rows

unique(dk$region)
#>  [1] NA                           "bankssts"                  
#>  [3] "caudal middle frontal"      "fusiform"                  
#>  [5] "inferior parietal"          "inferior temporal"         
#>  [7] "lateral occipital"          "lateral orbitofrontal"     
#>  [9] "middle temporal"            "pars opercularis"          
#> [11] "pars orbitalis"             "pars triangularis"         
#> [13] "postcentral"                "precentral"                
#> [15] "rostral middle frontal"     "superior frontal"          
#> [17] "superior parietal"          "superior temporal"         
#> [19] "supramarginal"              "temporal pole"             
#> [21] "transverse temporal"        "insula"                    
#> [23] "caudal anterior cingulate"  "corpus callosum"           
#> [25] "cuneus"                     "entorhinal"                
#> [27] "isthmus cingulate"          "lingual"                   
#> [29] "medial orbitofrontal"       "parahippocampal"           
#> [31] "paracentral"                "pericalcarine"             
#> [33] "posterior cingulate"        "precuneus"                 
#> [35] "rostral anterior cingulate" "frontal pole"
```

<sup>Created on 2020-09-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by Athanasiamo** [comment]
if you literally run the example I have above where it plots the p value, does it work?

**Comment by Athanasiamo** [comment]
No wait! You suddenly mention another package??

This is your problem!

The brainGraph package also has a dataset called `dk`. It is overriding the ggseg atlas data for `dk` if you are loading it after ggseg.

**Comment by gsborgeest** [comment]
Hey, I just got it, thank you! "Pre central" and "Post central" are now single words, but must have been separate ones in the past (or maybe they are in brainGraph but not in ggseg?), since all of this used to work. Anyway, I deleted brainGraoh again, re-imported the dk atlas names from ggseg and it is now working. Sorry again for your trouble!

**Comment by gsborgeest** [comment]
Thanks again!!

**Comment by Athanasiamo** [comment]
no worries. I had never heard of that package, do I didnt know. 

You can have them both installed, but need to be mindful in loading them in the same workflow.

You can always also explicitly call the data from one or the other using the syntax `package::data`

for example

```r
ggseg::dk  # explicitly call dk data from ggseg
brainGraph::dk # explicitly calls dk data from brainGraph
```
