### ISSUE TITLE
dkt area name consistency

### ISSUE THREAD

**Issue by Conxz** [LCBC-UiO/ggseg#19]
I found that the current area name for 'lateral orbito frontal' became 'lateral orbitofrontal' in the dkt.rda. Not sure whether this is on purpose. But this is not consistent with the another area's name 'medial orbito frontal'. I personally would keep the previous name 'lateral orbito frontal'.

**Comment by Athanasiamo** [comment]
Hi! Thank you for pointing this out. 

We have renamed in commit [0a9b27e](https://github.com/LCBC-UiO/ggseg/commit/0a9b27e489a3325c0a76eebe3bc44d4743b3a20e) the "medial orbito frontal" to "medial orbitofrontal", which is the correct naming.
