### ISSUE TITLE
Request for inferior and superior views for DKT

### ISSUE THREAD

**Issue by nvogt** [LCBC-UiO/ggseg#21]
Are there plans to include inferior or superior views for DKT? I have some results that I'd like to plot for the fusiform area, but it's barely visible from the medial or lateral views. Thanks!

**Comment by didacvp** [comment]
Hi,

Thanks for using the ggseg!
We can introduce extra views for the ggseg dkt atlas, but won’t be possible until early next week.
Best,
D

**Comment by nvogt** [comment]
Is there any update on this? Thanks for the great software!

**Comment by Athanasiamo** [comment]
Hi! I finally got to make an atlas for you based on polygon data @didacvp made.


```
ggseg(atlas = dkextra, mapping = aes(fill = region)) +
  scale_fill_brain("dk")
```
![image](https://user-images.githubusercontent.com/14014329/76342213-83c28500-62fe-11ea-979f-55e15fdf276d.png)

We are unsure if we want to keep this data in permanently, as it does not play well with `position = "stacked"` . But atleast you have something to work with. 

the atlas is names `dkextra` and you can get it with the ggsegExtra package. Be patient, it's a large package, it will take some time to download. 


`remotes::install_github("LCBC-UiO/ggsegExtra", "atlascreate")`

**Comment by nvogt** [comment]
This is perfect -- thank you so much!
