### ISSUE TITLE
accumbens-area in aseg atlas

### ISSUE THREAD

**Issue by OPMEDICS** [LCBC-UiO/ggseg#23]
Hi,
Thank you a lot for the nice work. 
I did not find the accumbens-area in the aseg atlas regions. Is it missing or under a different name? I tried a few possibilities, but did not work.
Kind regards,
OP

**Comment by Athanasiamo** [comment]
Hi!

Unfortunately, the subcortical structures are impossible to grab a shot of while vieweing them all. This means that a 2-dimensional rendering will be missing some structures.

We'd recommend you have a look at the [ggseg3d](https://github.com/LCBC-UiO/ggseg3d) instead, which renders the entire brain in 3d mesh, so you should be able to more easily find the areas you are interested in there.
