### ISSUE TITLE
submit `ggseg` package to the gallery of ggplot2 extensions? 

### ISSUE THREAD

**Issue by IndrajeetPatil** [LCBC-UiO/ggseg#28]
This will make it easy to discover the package for people looking to display segmented image in ggplot framework, who might run into the GitHub repo.

The instructions for how to so are here: https://github.com/ggplot2-exts/gallery

**Comment by Athanasiamo** [comment]
Hi! We have not submitted out package there because it is not a true extension, but rather a wrapper for ggplot2. When we manage to make a proper extension (like a geom or stat) we will do so! Thank you for the suggestion.
