### ISSUE TITLE
aseg output incomplete

### ISSUE THREAD

**Issue by mscott24** [LCBC-UiO/ggseg#32]
Hello, 

First, thank you for making this application. 

Second, I am having an issue with outputting aseg images. I am able to get the image with amygdala, caudate, hippocampus, lateral ventricle, pallidum, putamen, thalamus proper, and NA, but not the midline structures (cerebellum etc.). Has this problem been encountered before and if so, do you know a solution? This happens even when using the code from the paper:

ggseg(atlas="aseg", mapping=aes(fill=area)) + 
  theme(legend.justification=c(1,0), legend.position='bottom', legend.text = element_text(size = 5)) + guides(fill = guide_legend(ncol = 3))

My apologies if I'm missing something obvious. 

Warm regards, 
MRS

**Comment by Athanasiamo** [comment]
Hi! I need to alter the description on my blog which now shows an old way of working with ggseg. We have been improving it and did some changes in the names of the atlas columns due to conflicts when adding other functionality.  Please change `area` to `region` and this should work well.

To see updated instructions please confer with the package website: https://lcbc-uio.github.io/ggseg/

``` r
library(ggseg)
#> Loading required package: ggplot2
ggseg(atlas = aseg, mapping = aes(fill = region)) +
  theme(legend.justification = c(1,0), 
        legend.position = 'bottom', 
        legend.text = element_text(size = 5)) + 
  guides(fill = guide_legend(ncol = 3))
```

![](https://i.imgur.com/UWcsKrv.png)

<sup>Created on 2020-04-17 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mscott24** [comment]
Thank you for the quick response!

Still with that code, I am only able to get the left portion of that image and no midline view. When I look at the aseg atlas it is importing, it does not have the CC/cerebellum/other regions in the midline view. I'm assuming that is the issue? Is there a way to update the aseg atlas with those regions?

Warm regards, 
MRS

**Comment by Athanasiamo** [comment]
I dont know when you downloaded the library, but you could try re-installing `remotes::install_github("LCBC-UiO/ggseg")`

**Comment by mscott24** [comment]
All resolved now! Thank you - that was the issue. I downloaded the package through an old mirror apparently and now it is working.

**Comment by FHeeman92** [comment]
Hi! I fully agree, very nice application!
Unfortunately, I also have a problem with the aseg atlas, although it seems like I have downloaded the latest version. When I try installing ggseg again I get the message that "the SHA1 (9330d878) hasn't changed since last install."

The error I get is the following:  "Check for spelling mistakes in: right - cerebellum cortex, left - cerebellum cortex, right - cerebellum white matter, left - cerebellum white matter". I also get this error when I use the "CC" regions.

Do you know what might be going wrong?
Thanks!
Fiona

**Comment by Athanasiamo** [comment]
Hi.

I'm afraid you're not giving me alot of information to go on in terms of helping you. Can you look into making a reproducible example so I can better understand what you are doing and what is being outputted.

https://reprex.tidyverse.org/articles/articles/learn-reprex.html

**Comment by FHeeman92** [comment]
Hi, sorry, I'm very new to R. I tried to use the reprex link you send, but I'm not sure how to insert the output html page in this message, so I just pasted it.

`#Subcortical decreases in CBF
#get data
ALL <- read_excel("Final_file_ggseg_23102020subc_decr.xlsx")
#> Error in read_excel("Final_file_ggseg_23102020subc_decr.xlsx"): could not find function "read_excel"


results1 = data.frame(cbind(region=ALL$template,em=ALL$value, hemi=ALL$side),
                      stringsAsFactors=F)
#> Error in cbind(region = ALL$template, em = ALL$value, hemi = ALL$side): object 'ALL' not found


results1 %>% 
  ggseg(atlas=aseg,mapping=aes(fill=as.numeric(em)),
        colour="black",size=.8) +
  ggtitle("Subcortical decreases in CBF") +
  theme(plot.title = element_text(hjust=0.5)) +
  theme_brain()
#> Error in results1 %>% ggseg(atlas = aseg, mapping = aes(fill = as.numeric(em)), : could not find function "%>%"`

**Comment by FHeeman92** [comment]
Hi, I'm sorry, I'm very new to R and Github and the error I got in the reprex wasn't the same as the one I had in R.

`> ALL <- read_excel("Final_file_ggseg_23102020subc_decr.xlsx")
> 
> 
> results1 = data.frame(cbind(region=ALL$template,em=ALL$value, hemi=ALL$side),
+                       stringsAsFactors=F)
> 
> 
> results1 %>% 
+   ggseg(atlas=aseg,mapping=aes(fill=as.numeric(em)),
+         colour="black",size=.8) +
+   ggtitle("Subcortical decreases in CBF") +
+   theme(plot.title = element_text(hjust=0.5)) +
+   theme_brain()
Error in grid.Call.graphics(C_path, x$x, x$y, index, switch(x$rule, winding = 1L,  : 
  non-finite x or y in graphics path
In addition: Warning message:
In data_merge(.data, geobrain) :
  Some .data is not merged properly into the atlas. Check for spelling mistakes in: right - cerebellum, left - cerebellum, right - cerebellum white matter, left - cerebellum white matter`

**Comment by Athanasiamo** [comment]
reprex runs in a completely clean R environment. You will need to add the library calls for the packages you are using to make things work. In this case, you will need to call at least ggseg, readxl (?), and dplyr, it looks like to me.

**Comment by Athanasiamo** [comment]
Please the the below example with fixes to your problems

``` r
library(ggseg)
#> Loading required package: ggplot2
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

ALL <- tibble(
  template = c("amygdala", rep("cerebellum", 2),
               rep("cerebellum white matter", 2),
               rep("hippocampus", 2),
               rep("thalamus proper", 2),
               rep("ventral DC", 2)),
  value = c(rep(1, 5), rep(2,2), rep(1,4)),
  side = c("right", "right", "left", "right", 
           "left", "right", "left", "right", 
           "left", "right", "left")
)

results1 = tibble(region = ALL$template,
                  em = as.numeric(ALL$value), 
                  hemi = ALL$side)

# The cerebellum has no hemisphere, as it crosses them
# The hemisphere for these regions are set as "midline"
# also, there is no "cerebellum", it is "cerebellum cortex"
aseg %>% 
  filter(grepl("cerebellum", region))
#> # A tibble: 2 x 6
#>   atlas     hemi    region            side    label                ggseg        
#>   <chr>     <chr>   <chr>             <chr>   <fct>                <list>       
#> 1 midsagit… midline cerebellum cortex sagitt… right-cerebellum-wh… <tibble [210…
#> 2 midsagit… midline cerebellum white… sagitt… right-cerebellum-co… <tibble [37 …

# Alter your data to fit the atlas
results1 <- results1 %>% 
  mutate(hemi = ifelse(grepl("cerebellum", region), "midline", hemi),
         region = ifelse(region == "cerebellum", "cerebellum cortex", region))

results1 %>%
  ggseg(atlas = aseg, mapping = aes(fill=em),
        colour = "black", size = .8) +
  ggtitle("Subcortical decreases in CBF") +
  theme(plot.title = element_text(hjust=0.5)) +
  theme_brain()
```

![](https://i.imgur.com/5aZC0fy.png)

<sup>Created on 2020-10-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by Athanasiamo** [comment]
The cerebellum of course does have sides, but the freesurfer output does not distinguish them, which is why we solved it this way.

**Comment by FHeeman92** [comment]
That's great! Thank you so much Athanasiamo! I tried both cerebellum and cerebellum cortex to see if that was causing the error, but it had to do with the side definition. 
You made my day :-) thanks a lot for your time and help.
