### ISSUE TITLE
read_atlas_files

### ISSUE THREAD

**Issue by Jasmine1990** [LCBC-UiO/ggseg#33]
Thanks for this amazing package!

I have an issue with the "read_atlas_files". In my subj directory I have multiple time points for the same subject and the naming is "t1_IDnr_tp", where ID is the ID for the participant and tp is the time point. For instance I can have t1_1000_3 that is the subject 1000 at time 3. The issue with the read_atlas_files is that in the column "subject" I get all t1 and the label is 1000__bankssts (without the time point) and so on.
I was wondering how the participant's name is gather in the table under the column "subject" and if I can fix that without changing the name of the folder.

Thanks!
Jasmine

**Comment by Athanasiamo** [comment]
right! I can see how that can  make some  difficulties. 

I believe I made a change that should fix this issue for you. Please update ggseg and let me know if it worked!

**Comment by Jasmine1990** [comment]
worked like a charm! 

Thanks!
