### ISSUE TITLE
"mangled" yeo7 and yeo17 atlases

### ISSUE THREAD

**Issue by AthinaRA** [LCBC-UiO/ggseg#34]
Hi ggseg team

I seemed to have run into some issues with visualizing the Yeo rsFC networks. In particular - I have tried to first simply reproduce the figures per vignette ie without external data input. The resultant images however looked a little "mangled"  - pls see images below. Checking the atlas - it seems to me that there are void cortical parcels ie the white cutouts in the cortex. I could successfully visualize the DK and Glasser atlases ie it didn't look "mangled". I have tried reinstalling the atlases too - same outcome. I am not sure what I am doing something wrong here - pls find my code below. Please and thank you - Athina. 

# load ggseg and then ggsegExtra
library(ggseg)
library(ggseg3d)
install.packages("ggsegExtra")
library(ggsegExtra)

# get the atlases you want
ggseg_atlas_repos()   # take a look at the available atlases 
yeo_ggseg = ggseg_atlas_repos("LCBC-UiO/ggsegYeo2011")
install_ggseg_atlas(repo = yeo_ggseg$repo, source = yeo_ggseg$source)
library(ggsegYeo2011)

ggseg(atlas = "yeo17")   # check how atlas looks like
ggseg(atlas = "yeo7")
head(yeo7)   # take a look at df ie how data is stored

# vizualize
ggseg(atlas = "yeo7",  position = "stacked",
      mapping=aes(fill = region), colour="black") +
  scale_fill_brain("yeo7", package="ggsegYeo2011") +
  ggtitle("Yeo 7 resting-state networks")

ggseg(atlas = "yeo17",  position = "stacked",
      mapping=aes(fill = region), colour="black") +
  scale_fill_brain("yeo17", package="ggsegYeo2011") +
  ggtitle("Yeo 17 resting-state networks")

<img width="703" alt="Yeo7" src="https://user-images.githubusercontent.com/50332271/80094159-aed70000-855d-11ea-8446-5f0ff8bcdea8.png">
<img width="944" alt="Yeo17" src="https://user-images.githubusercontent.com/50332271/80094167-b3031d80-855d-11ea-94a8-cc6bc7cea292.png">
<img width="1603" alt="Yeo7_atlasdat" src="https://user-images.githubusercontent.com/50332271/80094178-b7c7d180-855d-11ea-827d-2b0805e2ee08.png">

**Comment by Athanasiamo** [comment]
Hi!

This seems like a combination of two things. 

1. your ggseg is old, you need to reinstall. `remotes::install_github("LCBC-UiO/ggseg")`
2. there was something wrong with the yeo17 atlas, the yeo7 atlas was fine but the outdated version was messing it up.

If you update both ggseg and ggsegYeo2011 now it should be fine.

**Comment by AthinaRA** [comment]
Many thanks Dr Mowinckel - all behaved after updating the above !!
