### ISSUE TITLE
Problem installing in R4.0 and R3.6.3

### ISSUE THREAD

**Issue by shalailahaas** [LCBC-UiO/ggseg#36]
Hi, 
I have tried multiple different things to try to install ggseg in R, but keep getting an error. 
I tried using both devtools and remotes to install ggseg after installing those packages along with ggplot2 using install.packages("ggplot2"). 
 
Then I tried to install ggseg: 
  > devtools::install_github("LCBC-UiO/ggseg", build_vignette=T)
Downloading GitHub repo LCBC-UiO/ggseg@master
    
   checking for file 'path\remotes72844aaf172c\LCBC-UiO-ggseg-0213c3d/DESCRIPTION' ...
  
√  checking for file 'path\remotes72844aaf172c\LCBC-UiO-ggseg-0213c3d/DESCRIPTION'
  
-  preparing 'ggseg':
   checking DESCRIPTION meta-information ...
  
   checking DESCRIPTION meta-information ... 
  
√  checking DESCRIPTION meta-information

-  installing the package to build vignettes

   creating vignettes ...
  
   creating vignettes ... 
  
E  creating vignettes (15.5s)
   --- re-building 'externalData.Rmd' using rmarkdown
   --- finished re-building 'externalData.Rmd'
   
   --- re-building 'freesurfer_files.Rmd' using rmarkdown
   Quitting from lines 11-20 (freesurfer_files.Rmd) 
   Error: processing vignette 'freesurfer_files.Rmd' failed with diagnostics:
   there is no package called 'here'
   --- failed re-building 'freesurfer_files.Rmd'
   
   --- re-building 'ggseg.Rmd' using rmarkdown
   --- finished re-building 'ggseg.Rmd'
   
   SUMMARY: processing the following file failed:
     'freesurfer_files.Rmd'
   
   Error: Vignette re-building failed.
   Execution halted

Error: Failed to install 'ggseg' from GitHub:
  System command 'Rcmd.exe' failed, exit status: 1, stdout + stderr (last 10 lines):
E> --- failed re-building 'freesurfer_files.Rmd'
E> 
E> --- re-building 'ggseg.Rmd' using rmarkdown
E> --- finished re-building 'ggseg.Rmd'
E> 
E> SUMMARY: processing the following file failed:
E>   'freesurfer_files.Rmd'
E> 
E> Error: Vignette re-building failed.
E> Execution halted

In lines 11-20 in freesurfer_files.Rmd, it seems to be trying to install a package called "here", which may actually be a variable.    
Error: processing vignette 'freesurfer_files.Rmd' failed with diagnostics: there is no package called 'here'

Thank you for your time!

-Shalaila

**Comment by Athanasiamo** [comment]
Hi @shalailahaas !

There is currently a small bug in the building of the vignettes that is stopping install. 

Please try 
```
devtools::install_github("LCBC-UiO/ggseg", build_vignette=FALSE)
```

**Comment by zqsha** [comment]
Hi Athanasiamo,

Thanks for developing such an amazing toolbox. I used devtools::install_github("LCBC-UiO/ggseg", build_vignette=FALSE) to successfully install this toolbox. But when I type the ggseg(), it just showed some words on the screen, but there is no brain in the output. Any thoughts to fix it? Thanks

Best,
Cain

**Comment by Athanasiamo** [comment]
Hi cain! Sorry you are experiencing issues. 

Can you take a screenshot of what you are seeing for me?

**Comment by zqsha** [comment]
Yeah, sure. Thanks for your help.
![Capture](https://user-images.githubusercontent.com/27337033/83874716-3a83a500-a736-11ea-9161-c20ea0256933.PNG)

**Comment by zqsha** [comment]
I have two versions of R, R-3.5.2 and R-3.6.0. I just now used R-3.6.0. Do I need to switch to R-3.5.2 ?

**Comment by Athanasiamo** [comment]
interesting! 

I'm surprised by this. It should work on 3.6.0 at least (since we developed most of it while using that version). What this image tells me is that the plot is picking up some but not all it should. 

you are seeing this by literally going: 

``` r
library(ggseg)
#> Loading required package: ggplot2
ggseg()
```

![](https://i.imgur.com/rOcSq6r.png)

<sup>Created on 2020-06-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by zqsha** [comment]
OK. Thanks. Maybe there is something wrong with my ggplot2. I will check that right now.

**Comment by Athanasiamo** [comment]
can you give me your `sessionInfo()` so I can have a look? 

I have not adapted ggseg to work with dpyr 1.0.0 yet, for instance, and there _might_ be something there.

**Comment by zqsha** [comment]
Yeah, sure.

> sessionInfo()
R version 3.6.0 (2019-04-26)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: openSUSE Leap 15.0

Matrix products: default
BLAS:   /usr/shared/apps/R/R-3.6.0/lib64/R/lib/libRblas.so
LAPACK: /usr/shared/apps/R/R-3.6.0/lib64/R/lib/libRlapack.so

Random number generation:
 RNG:     Mersenne-Twister
 Normal:  Inversion
 Sample:  Rounding

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] ggseg_1.5.4   ggplot2_3.2.1

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.4       tidyr_1.0.2      withr_2.1.2      assertthat_0.2.1
 [5] crayon_1.3.4     dplyr_0.8.4      grid_3.6.0       R6_2.4.1
 [9] lifecycle_0.1.0  gtable_0.3.0     magrittr_1.5     scales_1.1.0
[13] pillar_1.4.3     rlang_0.4.6      farver_2.0.3     lazyeval_0.2.2
[17] rstudioapi_0.11  vctrs_0.2.2      glue_1.4.0       purrr_0.3.3
[21] munsell_0.5.0    compiler_3.6.0   pkgconfig_2.0.3  colorspace_1.4-1
[25] tidyselect_1.0.0 tibble_2.1.3

**Comment by Athanasiamo** [comment]
your ggplot2 is somewhat older than mine, please give it an update and see if that helps. The remaining depending packages have _slight_ version differences, but not the types I would expect to show a difference.

If you just want to have a look at the atlas data, what does that look like for you? 

``` r
library(ggseg)
#> Loading required package: ggplot2
dk
#> # A tibble: 90 x 6
#>    atlas hemi  region              side    label                ggseg           
#>    <chr> <chr> <chr>               <chr>   <chr>                <list>          
#>  1 dk    left  <NA>                lateral <NA>                 <tibble [24 × 7…
#>  2 dk    left  bankssts            lateral lh_bankssts          <tibble [79 × 7…
#>  3 dk    left  caudal middle fron… lateral lh_caudalmiddlefron… <tibble [102 × …
#>  4 dk    left  fusiform            lateral lh_fusiform          <tibble [60 × 7…
#>  5 dk    left  inferior parietal   lateral lh_inferiorparietal  <tibble [116 × …
#>  6 dk    left  inferior temporal   lateral lh_inferiortemporal  <tibble [182 × …
#>  7 dk    left  lateral occipital   lateral lh_lateraloccipital  <tibble [85 × 7…
#>  8 dk    left  lateral orbitofron… lateral lh_lateralorbitofro… <tibble [70 × 7…
#>  9 dk    left  middle temporal     lateral lh_middletemporal    <tibble [188 × …
#> 10 dk    left  pars opercularis    lateral lh_parsopercularis   <tibble [82 × 7…
#> # … with 80 more rows
```

<sup>Created on 2020-06-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by zqsha** [comment]
Thanks. I will update ggplot2 and try if it works. For the output of atlas data,

> library(ggseg)
Loading required package: ggplot2
ggseg by default only loads atlases dkt and aseg. To install other available atlases, check out LCBC-UiO/ggsegExtra'
> dk
# A tibble: 90 x 6
   atlas hemi  region              side    label                ggseg
   <chr> <chr> <chr>               <chr>   <chr>                <list>
 1 dk    left  NA                  lateral NA                   <tibble [24  7?
 2 dk    left  bankssts            lateral lh_bankssts          <tibble [79  7?
 3 dk    left  caudal middle fron? lateral lh_caudalmiddlefron? <tibble [102  ?
 4 dk    left  fusiform            lateral lh_fusiform          <tibble [60  7?
 5 dk    left  inferior parietal   lateral lh_inferiorparietal  <tibble [116  ?
 6 dk    left  inferior temporal   lateral lh_inferiortemporal  <tibble [182  ?
 7 dk    left  lateral occipital   lateral lh_lateraloccipital  <tibble [85  7?
 8 dk    left  lateral orbitofron? lateral lh_lateralorbitofro? <tibble [70  7?
 9 dk    left  middle temporal     lateral lh_middletemporal    <tibble [188  ?
10 dk    left  pars opercularis    lateral lh_parsopercularis   <tibble [82  7?
# ? with 80 more rows

**Comment by lucasfr** [comment]
I am having a similar issue with the vignettes (R version 3.6.3). It only installs the package with the command suggested by @Athanasiamo.

**Comment by gsborgeest** [comment]
Hi @Athanasiamo , I'm having similar issues here. Running 

`devtools::install_github("LCBC-UiO/ggseg", build_vignette=FALSE)`

gives me the following error: 

```
`Downloading GitHub repo LCBC-UiO/ggseg@HEAD
√  checking for file 'C:\Users\sb09\AppData\Local\Temp\RtmpYvDIAG\remotes414c4870794\LCBC-UiO-ggseg-9330d87/DESCRIPTION' ... 
-  preparing 'ggseg':
√  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  looking to see if a 'data/datalist' file should be added
-  building 'ggseg_1.5.5.tar.gz'
   
Installing package into ‘C:/Users/sb09/Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)
* installing *source* package 'ggseg' ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
Error: (converted from warning) package 'ggplot2' was built under R version 3.6.3
Execution halted
ERROR: lazy loading failed for package 'ggseg'
* removing 'C:/Users/sb09/Documents/R/win-library/3.6/ggseg'
Error: Failed to install 'ggseg' from GitHub:
  (converted from warning) installation of package ‘C:/Users/sb09/AppData/Local/Temp/RtmpYvDIAG/file414c565e7c65/ggseg_1.5.5.tar.gz’ had non-zero exit status`

```

 Here is the `sessionInfo()`
```

R version 3.6.2 (2019-12-12)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=English_United Kingdom.1252 
[2] LC_CTYPE=English_United Kingdom.1252   
[3] LC_MONETARY=English_United Kingdom.1252
[4] LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] pillar_1.4.6      compiler_3.6.2    prettyunits_1.1.1 remotes_2.2.0    
 [5] tools_3.6.2       corrplot_0.84     testthat_2.3.2    pkgload_1.1.0    
 [9] digest_0.6.27     pkgbuild_1.1.0    nlme_3.1-142      memoise_1.1.0    
[13] lifecycle_0.2.0   tibble_3.0.4      gtable_0.3.0      lattice_0.20-38  
[17] pkgconfig_2.0.3   rlang_0.4.8       psych_2.0.9       Matrix_1.2-18    
[21] cli_2.1.0         rstudioapi_0.11   parallel_3.6.2    curl_4.3         
[25] pbivnorm_0.6.0    gridExtra_2.3     withr_2.3.0       dplyr_1.0.2      
[29] fs_1.5.0          desc_1.2.0        devtools_2.3.2    generics_0.0.2   
[33] vctrs_0.3.4       stats4_3.6.2      rprojroot_1.3-2   grid_3.6.2       
[37] tidyselect_1.1.0  glue_1.4.2        R6_2.4.1          processx_3.4.4   
[41] fansi_0.4.1       lavaan_0.6-7      sessioninfo_1.1.1 ggplot2_3.3.2    
[45] purrr_0.3.4       callr_3.5.1       magrittr_1.5      usethis_1.6.3    
[49] scales_1.1.1      backports_1.1.10  ps_1.4.0          ellipsis_0.3.1   
[53] mnormt_2.0.2      assertthat_0.2.1  colorspace_1.4-1  munsell_0.5.0    
[57] tmvnsim_1.0-2     crayon_1.3.4 


```
Any thoughts? Thank you!

**Comment by Athanasiamo** [comment]
Hi.

It looks like you have an issue with packages and R not being built under the same conditions. In particular, it looks like the ggplot2 version you have installed is intended for R 3.6.3 and up, while you are on R.3.6.2. While I thought that ggplot2 did not have great differences, there might be some mis-match in things. I'd recommend trying to update your R version, unless you have to stay on 3.6.2.

**Comment by Athanasiamo** [comment]
The issues with installing this package and package vignettes failing the install should now have been fixed by the new update.

**Comment by BenkoBob** [comment]
Hi. Very interesting tool. I tried to install "ggseg" into R but it fails.  "ggseg3d" and "ggsegextra" installed with no problems. I see that the prior issues should be solved, but I have tried both :"devtools::install_github("LCBC-UiO/ggseg", build_vignette=TRUE)" and "devtools::install_github("LCBC-UiO/ggseg", build_vignette=FALSE)" with no luck. I get the following error message. 

Error: Failed to install 'ggseg' from GitHub:
  (converted from warning) installation of package ‘C:/Users/AppData/Local/Temp/Rtmp0gUgPZ/file26202ca22d00/ggseg_1.6.00.tar.gz’ had non-zero exit status. 

Is this a problem with the package? I have the latest R-version (R version 4.0.2 (2020-06-22) for Windows.

**Comment by Athanasiamo** [comment]
This is not enough information for me to go on, I'm afraid. I dont know why it would fail, and the reason for failing is not included in your post. 

[R CMD check](https://github.com/LCBC-UiO/ggseg/runs/1556591815?check_suite_focus=true) is passing for windows running the latest R version, so I'm not sure why you would have troubles installing.

**Comment by violaholletein** [comment]
> s. I see that the prior issues should be solved, but I have tried both :"devtools::install_github("LCBC-UiO/ggseg", build_vignette=TRUE)" and "devtools::install_github("LCBC-UiO/ggseg", build_vignette=FALSE)" with no luck. I get the following error message.
> 
> Error: Failed to install 'ggseg' from GitHub:
> (converted from warning) installation of package ‘C:/Users/AppData/Local/Temp/Rtmp0gUgPZ/file26202ca22d00/ggseg_1.6.00.tar.gz’ had non-zero exit status.
> 
> Is this a problem with the package? I have the latest R-version (R version 4.0.2 (2020-06-22) for Windows.

Im having the same issue as this one, and from sessionInfo() I get this: 

```
R version 3.6.1 (2019-07-05)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS  10.16

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] ps_1.5.0          fansi_0.4.2       prettyunits_1.1.1 withr_2.4.0       rprojroot_2.0.2   crayon_1.3.4      assertthat_0.2.1  R6_2.5.0         
 [9] rlang_0.4.10      cli_2.2.0         curl_4.3          remotes_2.2.0     rstudioapi_0.13   callr_3.5.1       tools_3.6.1       glue_1.4.2       
[17] compiler_3.6.1    processx_3.4.5    pkgbuild_1.2.0  

```
Im not sure if this is enough info to figure out what is causing the issue?

**Comment by Athanasiamo** [comment]
Could you rather provide the error message you get when installing?

**Comment by violaholletein** [comment]
> remotes::install_github("LCBC-UiO/ggseg", build_vignettes = FALSE)
Downloading GitHub repo LCBC-UiO/ggseg@HEAD
✓  checking for file ‘/private/var/folders/2w/8zzp9bxx50x5mdkl0_8f30wc0000gn/T/RtmpmbzgS0/remotes17e94844e79a/LCBC-UiO-ggseg-3676c74/DESCRIPTION’ (356ms)
─  preparing ‘ggseg’:
✓  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  looking to see if a ‘data/datalist’ file should be added
─  building ‘ggseg_1.6.00.tar.gz’
   
* installing *source* package ‘ggseg’ ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
Error: (converted from warning) package ‘ggplot2’ was built under R version 3.6.2
Execution halted
ERROR: lazy loading failed for package ‘ggseg’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/ggseg’
Error: Failed to install 'ggseg' from GitHub:
  (converted from warning) installation of package ‘/var/folders/2w/8zzp9bxx50x5mdkl0_8f30wc0000gn/T//RtmpmbzgS0/file17e923c15487/ggseg_1.6.00.tar.gz’ had non-zero exit status

**Comment by Athanasiamo** [comment]
please update your ggplot2 first, then try installing again.

**Comment by violaholletein** [comment]
I have tried doing this with `update.packages("ggplot2")` but it gives the same error still

**Comment by Athanasiamo** [comment]
This command does not actually update a package the way you think. Try re-installing using `install.packages("ggplot2)`

**Comment by Athanasiamo** [comment]
Hi everyone. I have finally had time to work a little with this bug, which showed up a little out of the blue.

You should now be able to install ggseg with the following

`remotes::install_github("lcbc-uio/ggseg"` 

This is working locally for me, and also on 6 separate systems.
