### ISSUE TITLE
Wrong atlas?

### ISSUE THREAD

**Issue by GuidoGuberman** [LCBC-UiO/ggseg#38]
Hello,

First off, I just wanted to thank you for creating this amazing library! 

I have a question which may reflect more my lack of knowledge about atlases than a problem with your tool. I am working with the DKT parcellation (Klein & Tourville 2012, https://www.researchgate.net/figure/Regions-in-the-DKT-cortical-labeling-protocol-Cortical-regions-of-interest-included-in_fig2_233889622). In your documentation you talk about using the "DKT" parcellation (e.g.:  5 of your arxiv paper), but the labels seem to correspond more to the DK parcellation (e.g.: bank superior temporal is in DK, not DKT). Is it possible there is a mistake here? And if that is the case, would it be possible to implement the actual DKT parcellation? It would be immensely helpful!

Thanks,
Guido.

**Comment by Athanasiamo** [comment]
Hi Guido.

You are very correct, we have indeed previously been talking about the DK atlas, while calling it DKT. This was very much a mistake on our part. The atlas really is the Desikan-Killany atlas, not the DKT. 

The package (and its documentation) has renamed the atlas to `dk` instead in commit [/bfb027eae09](https://github.com/LCBC-UiO/ggseg/commit/bfb027eae09cc34c1772f371e7af46b1878c4876), and we are awaiting post-production on the manuscripts where this has also been fixed.

**Comment by GuidoGuberman** [comment]
Hi Athanasia,

Thank you for your quick reply.

Ok it's good to know that I wasn't missing anything. So to follow-up, are there any plans to implement the actual DKT parcellation in ggseg? Or is it perhaps something that has already been implemented in ggseg extra?

**Comment by Athanasiamo** [comment]
Its on my todo list to get it done. Now that we have a pipeline for making atlases in ggsegExtra I hope to get t it soon.

**Comment by GuidoGuberman** [comment]
Great, I look forward to it. Thanks for your help!
