### ISSUE TITLE
Questions about some functions

### ISSUE THREAD

**Issue by zqsha** [LCBC-UiO/ggseg#40]
Hi experts,

I have two questions about the settings.
1. Can I set the color of the center of the brain (the subcortical regions)?
2. I found there are two parts in the center of the brain (black arrows). Is there something to do with the DK atlas?
![Picture1](https://user-images.githubusercontent.com/27337033/88811496-eb4a7580-d1b6-11ea-9871-81c16fdd6dee.png)

Thanks,
Cain

**Comment by zqsha** [comment]
I found the example data (https://lcbc-uio.github.io/ggseg/articles/ggseg.html) do not display corpus callosum. However, when I run the same command line, it displays corpus callosum. Can I choose to turn off displaying corpus callosum? Thanks.

**Comment by Athanasiamo** [comment]
Hi!

Thanks for contacting us about this. The addition of the corpus callosum to the ggseg dk atlas is fairly new, but it is actually a part of the DK original atlas, and as such we find it should also be incorporated to the ggseg atlas. 

https://surfer.nmr.mgh.harvard.edu/fswiki/CorticalParcellation


You can specify the colour for the NA regions through the `na.value` option in `scale_fill_brain`

``` r
library(ggseg)
#> Loading required package: ggplot2

ggseg(atlas = dk, mapping = aes(fill = region)) + 
  scale_fill_brain("dk", na.value = "black") + 
  theme(legend.position = "bottom" , 
        legend.text = element_text(size = 7)) + 
  guides(fill = guide_legend(ncol = 3))
```

![](https://i.imgur.com/R4MdPgv.png)

<sup>Created on 2020-08-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by zqsha** [comment]
OK. Get it. Thanks a lot. I really appreciate.
