### ISSUE TITLE
error in aparc 2009s 

### ISSUE THREAD

**Issue by wangkangcheng** [LCBC-UiO/ggseg#41]
Hi, I try to plot with aparc.a2009s atlas with the following command

someData = data.frame(
  region = c("G and S frontomargin", "G and S occipital inf", "G and S subcentral","G front inf-Opercular"), 
  p =  sample(seq(0,.5,.001), 4),
  stringsAsFactors = FALSE)

ggseg(colour = "black",atlas = desterieux, mapping = aes(fill = p),.data=someData) +
  theme_void() +
 scale_fill_brain("desterieux", package = "ggsegDesterieux") +
  labs(title="Aparc 2009s plots rule", fill="p-value")

but, it reports the error: 
 Continuous value supplied to discrete scale

How can I solve it ?

thanks

**Comment by Athanasiamo** [comment]
Hi!

You cannot use 
`scale_fill_brain("desterieux", package = "ggsegDesterieux") ` when you are filling the polygons with values from *any other data source* than the `region` column in the atlas data. 

ggplot2 is telling you that you are trying to use discrete values (atlas map colours to regions) as a colour scale for a variable that is scalar (p values). This is not possible. If you use anything else that `region` for coloring, then you cannot use the `scale_brain` functions.

``` r
library(ggseg)
#> Loading required package: ggplot2
library(ggsegDesterieux)

someData = data.frame(
  region = c("G and S frontomargin", "G and S occipital inf", "G and S subcentral","G front inf-Opercular"),
  p = sample(seq(0,.5,.001), 4),
  stringsAsFactors = FALSE)

ggseg(colour = "black",atlas = desterieux, mapping = aes(fill = p),.data=someData) +
  theme_void() +
  labs(title="Aparc 2009s plots rule", fill="p-value")
```

![](https://i.imgur.com/U0dDyeo.png)

<sup>Created on 2020-08-17 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by wangkangcheng** [comment]
Great thanks for your response.
