### ISSUE TITLE
updates to package

### ISSUE THREAD

**Issue by pittnerdlab** [LCBC-UiO/ggseg#42]
Hello, is there a section where I can see updates to terminology in the package?  I recently upgraded my R version from 3.5.2 to 4.0.2 and I reinstalled ggseg.  I'm now having trouble getting old code to work. It looks like the term "region" is used instead of "area", correct?  I'm having trouble getting it to plot the effect size colors, did labels change?

sample code below

CT_group<-df %>%ggseg(mapping=aes(fill=as.numeric(dim)),color="black",size=0.5) + 
  scale_fill_gradient2(high="blue",low="red",  na.value="transparent",limits = c(min,max))+xlab("")+
  ylab("")+theme(legend.position = "none")+theme(axis.text.x=element_blank())

thank you for your time and for making this package, I love it
Maria

**Comment by Athanasiamo** [comment]
Hi.

You are correct in assuming we did some naming changes. We did swap region for area (to avoid confusion with the calculations of surface area). 

We ahve a changelog here: https://lcbc-uio.github.io/ggseg/news/index.html

which I notice I did not update with the last update! Sorry about that. We altered the names of a couple of regions, so they would be more correct. The full list of region names can be found within the atlas:

``` r

library(ggseg)
#> Loading required package: ggplot2

unique(dk$region)
#>  [1] NA                           "bankssts"                  
#>  [3] "caudal middle frontal"      "fusiform"                  
#>  [5] "inferior parietal"          "inferior temporal"         
#>  [7] "lateral occipital"          "lateral orbitofrontal"     
#>  [9] "middle temporal"            "pars opercularis"          
#> [11] "pars orbitalis"             "pars triangularis"         
#> [13] "postcentral"                "precentral"                
#> [15] "rostral middle frontal"     "superior frontal"          
#> [17] "superior parietal"          "superior temporal"         
#> [19] "supramarginal"              "temporal pole"             
#> [21] "transverse temporal"        "insula"                    
#> [23] "caudal anterior cingulate"  "corpus callosum"           
#> [25] "cuneus"                     "entorhinal"                
#> [27] "isthmus cingulate"          "lingual"                   
#> [29] "medial orbitofrontal"       "parahippocampal"           
#> [31] "paracentral"                "pericalcarine"             
#> [33] "posterior cingulate"        "precuneus"                 
#> [35] "rostral anterior cingulate" "frontal pole"
```

<sup>Created on 2020-09-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by Athanasiamo** [comment]
I believe before precentral and postcentral were in two words, but should in fact be single words.

Sorry for the inconvenience!
