### ISSUE TITLE
cortical and subcortical in one plot? 

### ISSUE THREAD

**Issue by ellenkimc** [LCBC-UiO/ggseg#44]
Hello, 

I am trying to download the R package ggseg with the following comands: 

install.packages("remotes")
remotes::install_github("LCBC-Uio/ggseg")

And this is the output: 
> install.packages("remotes")
Installing package into ‘C:/Users/Collee-Hermans/Documents/R/win-library/4.0’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.0/remotes_2.2.0.zip'
Content type 'application/zip' length 388636 bytes (379 KB)
downloaded 379 KB

package ‘remotes’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\Collee-Hermans\AppData\Local\Temp\Rtmpm8w8iL\downloaded_packages
> remotes::install_github("LCBC-Uio/ggseg")
Downloading GitHub repo LCBC-Uio/ggseg@HEAD
√  checking for file 'C:\Users\Collee-Hermans\AppData\Local\Temp\Rtmpm8w8iL\remotes18ec1831cb9\LCBC-UiO-ggseg-9330d87/DESCRIPTION' ...
-  preparing 'ggseg':
√  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  building 'ggseg_1.5.5.tar.gz'
   
Installing package into ‘C:/Users/Collee-Hermans/Documents/R/win-library/4.0’
(as ‘lib’ is unspecified)
* installing *source* package 'ggseg' ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
Error: (converted from warning) package 'ggplot2' was built under R version 4.0.2
Execution halted
ERROR: lazy loading failed for package 'ggseg'
* removing 'C:/Users/Collee-Hermans/Documents/R/win-library/4.0/ggseg'
Error: Failed to install 'ggseg' from GitHub:
  (converted from warning) installation of package ‘C:/Users/COLLEE~1/AppData/Local/Temp/Rtmpm8w8iL/file18ec1b522685/ggseg_1.5.5.tar.gz’ had non-zero exit status

So it gives me a non-zero exit status. How can I fix this? I tried installing it with the vignettes as well, but this gave me an error too. 

I hope someone knows how to install this! Thank you very much.
Ellen

**Comment by Athanasiamo** [comment]
I see you are on a windows computer, do you have RTools installed? 

Why did you alter the title of the issue? Did you manage to get it installed and have another issue?

**Comment by ellenkimc** [comment]
Hello, 

Yes I installed it in the end! It turned out that ggplot2 was installed on another version of R, which was the reason that ggseg could not be installed.

Yes I changed it because I had another question. Is it possible to have cortical and subcortical in one plot? I'd like to visualise the actual tracts for the subcortical part. I thought I needed the extra atlasses for this but I can't find which tracts are in the different atlases. I am specifically looking for an atlas which shows the IFOF and FAT too. Do you know which one can do this? 

Thank you!!
Ellen

**Comment by Athanasiamo** [comment]
Hi.

It is hard to know what you are after specifically here. But we have no atlases with both cortical and subcortical information, because these are almost impossible to plot together. There will be too little information retained by each of them to render helpful visualisation, in my opinion. 

Currently the only ggseg atlas I know of with tracts has the tracula tracts:

``` r
library(ggseg)
#> Loading required package: ggplot2
library(ggsegTracula)

ggseg(atlas = tracula, 
      mapping = aes(fill = region))
```

![](https://i.imgur.com/pUyYoLZ.png)

<sup>Created on 2020-09-29 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
