### ISSUE TITLE
Only Coronal Slice of Subcortical Atlas

### ISSUE THREAD

**Issue by alexandrammuir** [LCBC-UiO/ggseg#46]
Hello Dr. Mowinckel, 

First off, thank you for your amazing package! It has been incredibly useful.

My question isn't really an "issue", so I apologize if this is not the appropriate forum to post to. When using the subcortical atlas, we would really love to only display the coronal slice since our current study has no information on the corpus callosum / brain stem. Is there a way to only display the coronal slice with the ggseg package? I would appreciate any guidance you may have.

Best,
Alex

![Screen Shot 2020-10-05 at 2 35 11 PM](https://user-images.githubusercontent.com/67383688/95129455-40a38580-0718-11eb-83f7-2ca75d8df3d1.png)

**Comment by Athanasiamo** [comment]
HI!

You can use the `view` argument to control what slices are shows. And this also points to an issue I had fixed before, but has crept back in at some point. The coronal slice is misnamed "axial". We will fix that in a coming update, but for now specify "axial".

``` r
library(ggseg)
#> Loading required package: ggplot2

ggseg(atlas = aseg, view = "axial")
```

![](https://i.imgur.com/0AKlDTX.png)

<sup>Created on 2020-10-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
