### ISSUE TITLE
Plotting individual regions from Yeo atlas with scale_fill_brain gives error?

### ISSUE THREAD

**Issue by stong3** [LCBC-UiO/ggseg#50]
Hi,

Great package! I love it and I can't believe I didn't know about it before!

I am trying to plot the individual networks from the Yeo atlas to complement a figure on an upcoming scientific paper. However, I can't seem to use `scale_fill_brain("yeo7")` to color the regions of interest based on the original colors.

Here is the code I tried:
```
#Create a dataframe to hold the region we want to see (e.g. "control" network from Yeo Atlas)
my_data = data.frame(
  region = c("control"),
  region_to_image = c("control"),
  stringsAsFactors = FALSE
)

#Plot the brain using the yeo7 atlas
p <- ggplot(my_data) +
  geom_brain(atlas=yeo7, position=position_brain(hemi ~ side), mapping=aes(fill=region_to_image)) +
  scale_fill_brain("yeo7") +
  theme_classic()

p
```
However, I get the error:
`Error in brain_pal(name = name, ...) : yeo7 is not a valid palette name for brain_pal`

In the documentation, of "scale_fill_brain", it mentions that "yeo7" is an available option, but the error above seems to say the contrary.

When I try to do something similar but with the "dk" atlas, I can do it without any problem:
```
#Create a dataframe to hold the region we want to see (e.g. "cuneus" region from DK)
my_data = data.frame(
  region = c("cuneus"),
  region_to_fill = c("cuneus"),
  stringsAsFactors = FALSE
)

#Plot the brain using the dk atlas
p <- ggplot(my_data) +
  geom_brain(atlas=dk, position=position_brain(hemi ~ side), mapping=aes(fill=region_to_fill)) +
  scale_fill_brain("dk") +
  theme_classic()

p
```
Which gives me the file attached (File 1).

<img width="637" alt="File 1" src="https://user-images.githubusercontent.com/64271866/102284404-17feef80-3f02-11eb-947f-d9af13113202.png">

I was able to find a bypass by using integers instead to highlight the region of interest, go fetch the HEX number associated to a specific network and fill the region with `scale_fill_gradient()` instead:
```
#Create a dataframe to hold the region we want to see (e.g. "control" network from Yeo Atlas)
my_data = data.frame(
  region = c("control"),
  region_to_image = c(1),
  stringsAsFactors = FALSE
)

#Plot the brain using the yeo7 atlas
## Set a gradient to fill, but set the same color for low and high
p <- ggplot(my_data) +
  geom_brain(atlas=yeo7, position=position_brain(hemi ~ side), mapping=aes(fill=region_to_image)) +
  scale_fill_gradient(low="#E69422", high="#E69422") +
  theme_classic()

p
```
The result is attached here (File 2). It works, but the problem is the legend is not updated.

<img width="637" alt="File 2" src="https://user-images.githubusercontent.com/64271866/102284416-1e8d6700-3f02-11eb-8771-508f2028a6ac.png">

As such, I was wondering if I overlooked a setting or I did a mistake in the script? Or if perhaps that was a bug to fix in the function?

Thanks for all your help!

Frédéric

**Comment by Athanasiamo** [comment]
Hi!

You were quite close, and I realise we need to adapt our documentation better now that the new function is in place. Thank you for exposing this need. We are slowly transitioning away from the brain_pal objects, and have the palettes for each atlas built-in to the atlas object themselves. 

``` r
library(ggseg)
#> Loading required package: ggplot2
library(ggsegYeo2011)
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

#Create a dataframe to hold the region we want to see (e.g. "control" network from Yeo Atlas)
my_data = data.frame(
  region = c("control"),
  region_to_image = c("control"),
  stringsAsFactors = FALSE
)

#Plot the brain using the yeo7 atlas
p <- ggplot(my_data) +
  geom_brain(atlas=yeo7, 
             position=position_brain(hemi ~ side), 
             aes(fill=region_to_image)) +
  scale_fill_brain2(yeo7$palette) +
  theme_brain2()

p
#> merging atlas and data by 'region'
```

![](https://i.imgur.com/NkDilIo.png)

``` r

# Create a function to plot a single region
plot_region <- function(region, atlas){
  x = data.frame(
    region = region,
    region_to_fill = region,
    stringsAsFactors = FALSE
  )
  
  ggplot(x) +
    geom_brain(atlas = atlas, 
               show.legend = FALSE,
               position = position_brain(hemi ~ side), 
               aes(fill = region_to_fill)) +
    scale_fill_brain2(atlas$palette) +
    theme_brain2() +
    ggtitle(region)
}

# Test it on a single region
plot_region("control", yeo7)
#> merging atlas and data by 'region'
```

![](https://i.imgur.com/7CACeWy.png)

``` r

# create a list of plots, one per region in the atlas
p <- lapply(brain_regions(yeo7), 
            plot_region, 
            atlas = yeo7)

# Use patchwork to wrap them all into one
patchwork::wrap_plots(p)
#> merging atlas and data by 'region'
#> merging atlas and data by 'region'
#> merging atlas and data by 'region'
#> merging atlas and data by 'region'
#> merging atlas and data by 'region'
#> merging atlas and data by 'region'
#> merging atlas and data by 'region'
```

![](https://i.imgur.com/3woV6CN.png)

<sup>Created on 2020-12-16 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by stong3** [comment]
Thank you so much for your quick reply! I did try to use `yeo$palette` in `scale_fill_brain()` but I did not try it with with `scale_fill_brain2()`. 

It now works great on my end! 

Also thanks for the extra code to use with patchwork: I had also never worked with patchwork before and I love it!
