### ISSUE TITLE
Missing Value where TRUE/FALSE Needed

### ISSUE THREAD

**Issue by alexandrammuir** [LCBC-UiO/ggseg#54]
Hello! 

I am trying to use the ggseg package to highlight some ROIs that were significant in some linear models that were run previously. I have created this dataframe that lists the significant ROIs. I added the "dummy" variable to use as a fill variable. I just want all of these ROIs to be highlighted in the same color.
![Screen Shot 2021-03-12 at 9 36 15 AM](https://user-images.githubusercontent.com/67383688/110970020-8fcc9280-8316-11eb-9c2e-fc768b288d10.png)

However, when I try the following command
`  ggseg(.data = common_filtered, atlas = "dk", mapping = aes(fill = dummy), color = "white", hemisphere = "left")+
      theme_void()`

I am getting the following error message: 
`Error in if (!after) c(values, x) else if (after >= lengx) c(x, values) else c(x[1L:after],  : 
  missing value where TRUE/FALSE needed`

Would you be willing to provide some support on this issue? I assume it's something my syntax or how my dataframe is set up, but I can't quite figure it out. I would appreciate any help you may be able to provide!

**Comment by alexandrammuir** [comment]
Ah! I feel very silly. I thought that the ROI had to be labeled "ROI" but looking back at it it needs to be "label" The error message is gone now. Thank you!

**Comment by Athanasiamo** [comment]
THanks for getting back to us and closing the issue. Sorry we didnt get to you sooner, but very happy you sorted it out!
